"""Runtime configuration for the monolithic VLMB Music Bot."""

import os


def _env(name: str, default: str = "") -> str:
    return os.getenv(name, default)


TELEGRAM_BOT_TOKEN = _env("TELEGRAM_BOT_TOKEN", "").strip()
YANDEX_TOKEN = _env("YANDEX_TOKEN", "").strip()
VK_TOKEN = _env("VK_TOKEN", "").strip()
LASTFM_API_KEY = _env("LASTFM_API_KEY", "").strip()

# Access control.
OWNER_ID = 0
ADMIN_IDS = [7250728575]

# SQLite files. Paths are intentionally unchanged.
STATS_DB_PATH = "bot_stats.db"
TG_FILE_CACHE_DB = "bot_stats.db"
VK_TOKENS_DB_PATH = "vk_tokens.db"
DB_WAL_MODE = True
DATABASE_TIMEOUT = 20

# Redis and transient user/search sessions.
REDIS_URL = _env("REDIS_URL", "redis://localhost:6379/0")
REDIS_MAX_CONNECTIONS = 80
REDIS_TIMEOUT = 3
SESSION_REDIS_PREFIX = "vlmb:sess:"
SESSION_TTL_SECONDS = 1200
MAX_CACHED_SESSIONS = 2000
SESSION_CLEANUP_INTERVAL = 60
SEARCH_SESSION_TIMEOUT = 900
USER_STATE_TIMEOUT = 300

# Per-user limits: action -> (requests, window_seconds).
RATE_LIMITS = {
    "search": (45, 60),
    "download": (25, 60),
    "ym_search": (20, 60),
}
COOLDOWN_SECONDS = 0.2
BAN_CACHE_REFRESH_SECONDS = 30

# Logging and process lifecycle.
LOG_LEVEL = "INFO"
LOG_FILE = "bot-debug.log"
LOG_MAX_BYTES = 10 * 1024 * 1024
LOG_BACKUP_COUNT = 5
INSTANCE_LOCK_FILE = ""

# Shared HTTP client.
USER_AGENT = "KateMobileAndroid/51.1-442 (Android 11; SDK 30; arm64-v8a; Samsung SM-G991B; ru_RU)"
REQUEST_TIMEOUT = 25
HTTP_CONNECT_TIMEOUT = 8
HTTP_SOCK_CONNECT_TIMEOUT = 8
HTTP_SOCK_READ_TIMEOUT = 25
HTTP_LIMIT_PER_HOST = 0
MAX_HTTP_CONNECTIONS = 160
HTTP_KEEPALIVE_TIMEOUT = 300
DNS_CACHE_TTL = 1800

# Telegram Bot API client.
TELEGRAM_CONNECT_TIMEOUT = 10
TELEGRAM_READ_TIMEOUT = 25
TELEGRAM_WRITE_TIMEOUT = 25
TELEGRAM_POOL_TIMEOUT = 10
TELEGRAM_CONNECTION_POOL_SIZE = 80
TELEGRAM_CONCURRENT_UPDATES = 12
TELEGRAM_API_RETRIES = 3
TELEGRAM_API_RETRY_BASE_DELAY = 0.7
ENABLE_CONNECTION_POOL = True

# Admin broadcast and group registry UI.
BROADCAST_SEND_DELAY = 0.05
ADMIN_GROUPS_PAGE_SIZE = 8

# Input and file limits.
MAX_QUERY_LENGTH = 100
MAX_FILENAME_LENGTH = 64
MAX_FILE_SIZE = 50 * 1024 * 1024

# Temporary files and periodic cleanup.
TEMP_DIR_PREFIX = "music_bot_"
TEMP_FILE_MAX_AGE = 900
CLEANUP_INTERVAL = 900
CHAT_SEMAPHORE_TTL = 3600
DIGEST_LOCK_TTL = 3600

# Cache limits.
CACHE_TTL = 3600
ASYNC_CACHE_LOCAL_MAX_ITEMS = 7000
ASYNC_CACHE_DEFAULT_TTL = 3600
CHAT_MEMBER_CACHE_TTL = 300
TG_FILE_ID_LOCAL_CACHE_MAX = 80000

# Search routing.
ENABLE_VK_MUSIC = True
ENABLE_YANDEX_MUSIC = True
ENABLE_YOUTUBE_MUSIC = True
SOURCE_PRIORITY = "vk_first"  # fastest | yandex_first | vk_first | youtube_first
MAX_SEARCH_RESULTS = 1200
MERGE_LIMIT_MULTIPLIER = 2
SEARCH_CACHE_VERSION = "v2_youtube"

# VK Music.
VK_API_URL = "https://api.vk.com/method/audio.search"
VK_API_VERSION = "5.131"
VK_TIMEOUT = 4
VK_SEARCH_RETRIES = 3
VK_RETRY_BACKOFF = 0.35
VK_SEARCH_SORT = 2
VK_SEARCH_AUTO_COMPLETE = 1
VK_TOKEN_USAGE_FLUSH_SECONDS = 60

# Yandex Music.
YM_SEARCH_TIMEOUT = 3
YM_PREFERRED_MAX_BITRATE_KBPS = 192
YANDEX_CONCURRENCY = 8
YM_SYNC_MAX_WORKERS = 12

# YouTube / yt-dlp. ffmpeg is optional but required for codec conversion.
YOUTUBE_SEARCH_TIMEOUT = 15
YOUTUBE_DOWNLOAD_TIMEOUT = 180
YOUTUBE_CONCURRENCY = 2
YOUTUBE_MAX_SEARCH_RESULTS = 40
YOUTUBE_SEARCH_RETRIES = 2
YOUTUBE_DOWNLOAD_RETRIES = 3
YOUTUBE_RETRY_SLEEP = 1.0
YOUTUBE_AUDIO_FORMAT = "bestaudio[ext=m4a]/bestaudio/best"
YOUTUBE_AUDIO_CODEC = "mp3"  # Empty string disables ffmpeg conversion.
YOUTUBE_AUDIO_QUALITY = "192"
YOUTUBE_FFMPEG_LOCATION = ""  # Empty string searches PATH.
YOUTUBE_COOKIE_FILE = ""

# Search result UI and background enrichment.
SONGS_PER_PAGE = 10
GROUP_CHAT_RESULTS_COUNT = 5
GROUP_CHAT_BEST_CACHE_COUNT = 30
BUTTON_TEXT_MAX_LENGTH = 48
BG_ENRICH_SEARCH = True
SESSION_ENRICH_LIMIT = 24
BG_ENRICH_CONCURRENCY = 2

# Downloads and Telegram file_id reuse.
MAX_CONCURRENT_DOWNLOADS = 5
AUDIO_MEMORY_BUDGET_MB = 512
MAX_CONCURRENT_DOWNLOADS_GROUP = 3
MAX_CONCURRENT_DOWNLOADS_PRIVATE = 6
DOWNLOAD_TIMEOUT = 30
DOWNLOAD_RETRIES = 4
DOWNLOAD_RETRY_BASE_DELAY = 0.7
DOWNLOAD_RETRY_MAX_DELAY = 6.0
DOWNLOAD_ALL_WORKERS = 0
DOWNLOAD_ALL_LIMIT = 60
TRACK_CREDIT_CAPTION = 'Скачано через <a href="https://t.me/VLMB_1_bot">VLMB</a>'

# User history.
HISTORY_LIMIT = 20

# Last.fm similar artists.
POPULAR_TRACKS_LIMIT = 15
SIMILAR_ARTISTS_LIMIT = 8
LASTFM_BASE_URL = "https://ws.audioscrobbler.com/2.0/"
LASTFM_BATCH_SIZE = 12
LASTFM_REQUEST_DELAY = 0.03

# Deezer charts and user mixes.
DEEZER_API_BASE_URL = "https://api.deezer.com"
DEEZER_TIMEOUT = 10
DEEZER_CONCURRENCY = 4
USER_MIX_NO_REPEAT_DAYS = 7

# Scheduled group digests.
DIGEST_TIMEZONE = "Europe/Amsterdam"
DIGEST_MAX_PER_GROUP = 12
DIGEST_NO_REPEAT_DAYS = 120
DIGEST_TEST_COUNTS_AS_SENT = True
DIGEST_SOURCE_PRIORITY = "yandex_first"
DIGEST_SOURCE_SEARCH_LIMIT = 16
DIGEST_MAX_CANDIDATE_ATTEMPTS = 60
DIGEST_DOWNLOAD_CONCURRENCY = 3
DIGEST_DOWNLOAD_TIMEOUT = 10.0
DIGEST_DOWNLOAD_RETRIES = 1
DIGEST_YM_DOWNLOAD_TIMEOUT = 16.0
DIGEST_YOUTUBE_DOWNLOAD_TIMEOUT = 45.0
DIGEST_BATCH_DELAY = 0.25
DIGEST_AUDIO_INDEX_TTL = 300
DIGEST_AUDIO_INDEX_LIMIT = 100000

# Keepalive after idle periods.
KEEPALIVE_IDLE_SECONDS = 120
KEEPALIVE_INTERVAL_SECONDS = 300
KEEPALIVE_WARMUP_QUERY = "music"

# Admin Excel file_id warmup.
EXCEL_WARMUP_TRACKS_PER_ARTIST = 5
EXCEL_WARMUP_MIN_TRACKS_PER_ARTIST = 1
EXCEL_WARMUP_MAX_ARTISTS = 1_000_000
EXCEL_WARMUP_CONCURRENCY = 2
EXCEL_WARMUP_SEND_DELAY = 0.15
